version: "3"
services:
  rollup-full-node:
    image: 737797969628.dkr.ecr.us-east-2.amazonaws.com/optimism/rollup-full-node:latest
    depends_on: [ "geth_l2" ]
    volumes:
      - full-node-data:/mnt/full-node:rw
      - l1-node-data:/mnt/l1-node:rw
      - l2-node-data:/mnt/l2-node:rw
    ports:
      - 8545:8545
    environment:
      - OPCODE_WHITELIST_MASK
      - L1_SEQUENCER_MNEMONIC
      - L2_TO_L1_MESSAGE_RECEIVER_ADDRESS
      - L2_TO_L1_MESSAGE_FINALITY_DELAY_IN_BLOCKS
      - L2_RPC_SERVER_HOST
      - L2_RPC_SERVER_PORT
      - L2_WALLET_MNEMONIC
      - L2_WALLET_PRIVATE_KEY_PATH=/mnt/l2-node/private_key.txt
      - LOCAL_L1_NODE_PORT
      - LOCAL_L1_NODE_PERSISTENT_DB_PATH=/mnt/l1-node
      - L2_NODE_WEB3_URL=http://0.0.0.0:9545/

    logging:
      driver: awslogs
      options:
        awslogs-group: rollup-full-node
        awslogs-region: us-east-2
        awslogs-stream-prefix: l2-rpc-server

  geth_l2:
    image: 737797969628.dkr.ecr.us-east-2.amazonaws.com/optimism/geth:latest
    volumes:
      - l2-node-data:/mnt/l2-node/l2:rw
    environment:
      - VOLUME_PATH=/mnt/l2-node/l2
      - HOSTNAME=0.0.0.0
      - PORT=9545
      - NETWORK_ID=108
      - KEYSTORE_PATH_SUFFIX=/keystore
      - SEALER_PRIVATE_KEY_PATH_SUFFIX=/sealer_private_key.txt
      - PRIVATE_KEY_PATH_SUFFIX=/private_key.txt
      - ADDRESS_PATH_SUFFIX=/address.txt
      - SEALER_ADDRESS_PATH_SUFFIX=/sealer_address.txt
      - INITIAL_BALANCE=0x200000000000000000000000000000000000000000000000000000000000000
      - GENISIS_PATH=etc/rollup-fullnode.json
      - SETUP_RUN_PATH_SUFFIX=/setup_run.txt
    ports:
      - 9545:9545
    
    logging:
      driver: awslogs
      options:
        awslogs-group: rollup-full-node
        awslogs-region: us-east-2
        awslogs-stream-prefix: l2-node

volumes:
  full-node-data:
  l1-node-data:
  l2-node-data:

