version: "3"

services:

  # Look at packages/rollup-core/README.md for info on configuration
  microservices:
    volumes:
      - l1-node-data:/mnt/l1-node:rw
      - l2-node-data:/mnt/l2-node:rw
    build:
      context: .
      dockerfile: Dockerfile.services
    environment:
# Postgres
      - POSTGRES_HOST=posgres               # (Required) The host DNS entry / IP for the postgres DB
      - POSTGRES_PORT                       # The port for postgres (defaults to 5432)
      - POSTGRES_USER=test                  # (Required) The user to use to connect to the db
      - POSTGRES_PASSWORD=test              # (Required) The password to use to connect to the db
      - POSTGRES_DATABASE                   # The database name to connect to (defaults to `rollup`)
      - POSTGRES_CONNECTION_POOL_SIZE       # The connection pool size for postgres (defaults to 20)
      - POSTGRES_USE_SSL                    # Set to anything to indicate that SSL should be used in the connection
# L1 Node
      - L1_NODE_INFURA_NETWORK              # The Infura network for the connection to the L1 node
      - L1_NODE_INFURA_PROJECT_ID           # The Infura project ID for the connection to the L1 node
      - L1_NODE_WEB3_URL                    # The URL of the L1 node
      - FINALITY_DELAY_IN_BLOCKS            # The number of block confirmations required to consider a transaction final on L1
# L2 Node
      - L2_NODE_WEB3_URL                    # The URL of the L2 node
# L1 Submitters
      - L1_SEQUENCER_PRIVATE_KEY            # The private key to use to submit Sequencer Transaction / State Batches

# TODO: FINISH THIS

  postgres:
    build:
      context: ./db/
      dockerfile: db.dockerfile
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432

volumes:
  l1-node-data:
  l2-node-data:








