version: "3"

services:

  rollup-full-node:
    volumes:
       - full-node-data:/mnt/full-node:rw
       - l1-node-data:/mnt/l1-node:rw
       - l2-node-data:/mnt/l2-node:rw
    depends_on:
      - geth_l2
#      - geth_l1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      - CLEAR_DATA_KEY=3
      - STARTUP_WAIT_TIMEOUT=30
      - OPCODE_WHITELIST_MASK
      - LOCAL_L1_NODE_PORT
      - LOCAL_L1_NODE_PERSISTENT_DB_PATH=/mnt/l1-node
      - L1_NODE_INFURA_NETWORK
      - L1_NODE_INFURA_PROJECT_ID
      - L1_NODE_WEB3_URL
      - L1_SEQUENCER_PRIVATE_KEY
      - L1_SEQUENCER_MNEMONIC
      - L1_EARLIEST_BLOCK
      - L1_TO_L2_TRANSACTION_PASSER_ADDRESS
      - L2_TO_L1_MESSAGE_RECEIVER_ADDRESS
      - L2_TO_L1_MESSAGE_FINALITY_DELAY_IN_BLOCKS
      - L2_RPC_SERVER_HOST
      - L2_RPC_SERVER_PORT
      - L2_RPC_SERVER_PERSISTENT_DB_PATH=/mnt/full-node/level
      - L2_WALLET_PRIVATE_KEY=0x29f3edee0ad3abf8e2699402e0e28cd6492c9be7eaab00d732a791c33552f797
      - L2_WALLET_MNEMONIC
      - L2_WALLET_PRIVATE_KEY_PATH
      - L2_NODE_WEB3_URL=http://geth_l2:9545/
#      - LOCAL_L2_NODE_PERSISTENT_DB_PATH=/mnt/l2-node/

  geth_l2:
    volumes:
       - l2-node-data:/mnt/l2-node/l2:rw
    build:
      context: docker/geth
      dockerfile: Dockerfile
    environment:
      - CLEAR_DATA_KEY=3
      - VOLUME_PATH=/mnt/l2-node/l2
      - HOSTNAME=geth_l2
      - PORT=9545
      - NETWORK_ID=108
    expose:
      - "9545"
    ports:
      - 9545:9545
#
#  geth_l1:
#    volumes:
#      - l1-node-data:/mnt/l1-node/l1
#    build:
#      context: docker/geth
#      dockerfile: Dockerfile
#    environment:
#      - VOLUME_PATH=/mnt/l1-node/l1
#    expose:
#      - "8545"

  graph-node:
    build:
      context: docker/the-graph
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres:5432
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'ovm:http://rollup-full-node:8545'
      RUST_LOG: info
      OVM_URL_WITH_PORT: 'http://rollup-full-node:8545'
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ipfs-data:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  full-node-data:
  l1-node-data:
  l2-node-data:
  postgres-data:
  ipfs-data:
