version: "3.7"

services:

  rollup-full-node:
    volumes:
       - .:/mnt/full-node:rw
       - l1-node-data:/mnt/l1-node:rw
       - l2-node-data:/mnt/l2-node:rw
    depends_on:
      - geth_l2
#      - geth_l1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      - CLEAR_DATA_KEY=3
      - STARTUP_WAIT_TIMEOUT=30
      - OPCODE_WHITELIST_MASK
      - LOCAL_L1_NODE_PORT
      - LOCAL_L1_NODE_PERSISTENT_DB_PATH=/mnt/l1-node
      - L1_NODE_INFURA_NETWORK
      - L1_NODE_INFURA_PROJECT_ID
      - L1_NODE_WEB3_URL
      - L1_SEQUENCER_PRIVATE_KEY
      - L1_SEQUENCER_MNEMONIC
      - L1_EARLIEST_BLOCK
      - L1_TO_L2_TRANSACTION_PASSER_ADDRESS
      - L2_TO_L1_MESSAGE_RECEIVER_ADDRESS
      - L2_TO_L1_MESSAGE_FINALITY_DELAY_IN_BLOCKS
      - L2_RPC_SERVER_HOST
      - L2_RPC_SERVER_PORT
      - L2_RPC_SERVER_PERSISTENT_DB_PATH=/mnt/full-node/level
      - L2_WALLET_PRIVATE_KEY=0x29f3edee0ad3abf8e2699402e0e28cd6492c9be7eaab00d732a791c33552f797
      - L2_WALLET_MNEMONIC
      - L2_WALLET_PRIVATE_KEY_PATH
      - L2_NODE_WEB3_URL=http://geth_l2:9545/
#      - LOCAL_L2_NODE_PERSISTENT_DB_PATH=/mnt/l2-node/

  geth_l2:
    volumes:
       - l2-node-data:/mnt/l2-node/l2:rw
    build:
      context: docker/geth
      dockerfile: Dockerfile
    environment:
      - CLEAR_DATA_KEY=3
      - VOLUME_PATH=/mnt/l2-node/l2
      - HOSTNAME=geth_l2
      - PORT=9545
      - NETWORK_ID=108
    expose:
      - "9545"
    ports:
      - 9545:9545
#
#  geth_l1:
#    volumes:
#      - l1-node-data:/mnt/l1-node/l1
#    build:
#      context: docker/geth
#      dockerfile: Dockerfile
#    environment:
#      - VOLUME_PATH=/mnt/l1-node/l1
#    expose:
#      - "8545"

volumes:
  full-node-data:
  l1-node-data:
  l2-node-data:
