version: "3"
networks:
  external:
    external: true
  internal:
services:
  rollup-fullnode:
    volumes:
       - geth-data:/mnt/geth/l2
    depends_on:
      - geth_l2
      - geth_l1
    networks:
      - internal
      - external
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      L1_WEB3_URL: http://geth_l1:8545/
      L2_WEB3_URL: http://geth_l2:8545/
      VOLUME_PATH: /mnt/geth/l2
  geth_l2:
    volumes:
       - geth-l2-data:/mnt/geth/l2
    networks:
      - internal
    build:
      context: docker/geth
      dockerfile: Dockerfile
    environment:
      VOLUME_PATH: /mnt/geth/l2
  geth_l1:
    volumes:
      - geth-l1-data:/mnt/geth/l1
    networks:
      - internal
    build:
      context: docker/geth
      dockerfile: Dockerfile
    environment:
      VOLUME_PATH: /mnt/geth/l1
volumes:
  - geth-l2-data:
  - geth-l1-data:
