version: "3"
networks:
  frontend:
    external: true
  backend:
services:
  rollup-fullnode:
    volumes:
       - geth-data:/root/.ethereum
    depends_on:
      - geth
    networks:
      - backend
      - frontend
    build:
      context: packages/rollup-full-node
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      WEB3_URL: http://geth:8545/
  geth:
    volumes:
       - geth-data:/root/.ethereum
    networks:
      - backend
    build:
      context: docker/geth
      dockerfile: Dockerfile
volumes:
  geth-data:
