version: "3"
services:
  geth_l2:
    image: <aws_account_id>.dkr.ecr.us-east-2.amazonaws.com/optimism/geth:synthetix-prod
    volumes:
      - l2-node-data:/mnt/l2-node/l2:rw
    environment:
      - CLEAR_DATA_KEY
      - VOLUME_PATH=/mnt/l2-node/l2
      - HOSTNAME=0.0.0.0
      - PORT=9545
      - NETWORK_ID=108
    ports:
      - 9545:9545

    logging:
      driver: awslogs
      options:
        awslogs-group: sythetix-prod-geth
        awslogs-region: us-east-2
        awslogs-stream-prefix: geth

volumes:
  l2-node-data:

