Vault:
  Config:
    ClusterName: "immutajeff"
    LogLevel: "debug"
  Seal:
    Project: "immutajeff-vault"
    Region: "global"
    KeyRing: "immutajeff-keyring"
    Key: "immutajeff-key"

server:
  image:
    repository: vault # TODO: will change to the omgnetwork/vault image
    tag: "1.5.0" # TODO: will change to the appropriate tag for omgnetwork/vault
    pullPolicy: IfNotPresent

  extraEnvironmentVars:
    GOOGLE_REGION: global
    GOOGLE_PROJECT: immutajeff-vault
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/credentials.json

  extraVolumes:
    - type: secret
      name: "kms-creds"
