global:
  tlsDisable: false
  certSecretName: omgnetwork-certs-b8k72gm922

injector:
  enabled: false

server:
  auditStorage:
    enabled: true

  ha:
    enabled: true
    replicas: 5

    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = false
        log_level = "info"
        cluster_name = "vault-cluster-0827"

        listener "tcp" {
          tls_disable = {{ .Values.global.tlsDisable }}
          tls_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
          tls_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"

          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        seal "gcpckms" {
          region      = "us-west2"
          project     = "vault-cluster-0827"
          key_ring    = "omgnetwork-vault-keyring"
          crypto_key  = "omgnetwork-vault-unseal-key"
        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "https://vault-0.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
          }

          retry_join {
            leader_api_addr = "https://vault-1.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
          }

          retry_join {
            leader_api_addr = "https://vault-2.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
          }

          retry_join {
            leader_api_addr = "https://vault-3.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
          }

          retry_join {
            leader_api_addr = "https://vault-4.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
          }
        }

        service_registration "kubernetes" {}
  image:
    repository: vault # TODO: will change to the omgnetwork/vault image
    tag: "1.5.2" # TODO: will change to the appropriate tag for omgnetwork/vault
    pullPolicy: IfNotPresent

  extraEnvironmentVars:
    GOOGLE_REGION: us-west2
    GOOGLE_PROJECT: vault-cluster-0827
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/kms_account.key.json

  extraVolumes:
    - type: secret
      name: "kms-creds"
    - type: secret
      name: "omgnetwork-certs-b8k72gm922"

  affinity: null

  dev:
    enabled: false

  standalone:
    enabled: false

ui:
  enabled: false
