global:
  tlsDisable: false
  certSecretName: omgnetwork-certs-ck6hgfbb79
injector:
  enabled: false
server:
  auditStorage:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
  service:
    enabled: true
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: Internal
  ha:
    enabled: true
    replicas: 5
    raft:
      enabled: true
      setNodeId: true
      config: |-
        ui = false
        log_level = "info"
        cluster_name = "omgnetwork-cluster"

        listener "tcp" {
            tls_disable = {{ .Values.global.tlsDisable }}
            tls_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            tls_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"

            address = "[::]:8200"
            cluster_address = "[::]:8201"
        }

        seal "gcpckms" {
            region      = "us-central1"
            project     = "omgnetwork-288020"
            key_ring    = "omgnetwork-vault-keyring"
            crypto_key  = "omgnetwork-vault-unseal-key"
        }

        storage "raft" {
            path = "/vault/data"

            retry_join {
            leader_api_addr = "https://vault-0.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
            }

            retry_join {
            leader_api_addr = "https://vault-1.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
            }

            retry_join {
            leader_api_addr = "https://vault-2.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
            }

            retry_join {
            leader_api_addr = "https://vault-3.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
            }

            retry_join {
            leader_api_addr = "https://vault-4.vault-internal.default.svc.cluster.local:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.crt"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.key"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca.crt"
            }
        }
  image:
    repository: vault # TODO: will change to the omgnetwork/vault image
    tag: "1.5.2" # TODO: will change to the appropriate tag for omgnetwork/vault
    pullPolicy: IfNotPresent
  extraEnvironmentVars:
    GOOGLE_REGION: us-central1
    GOOGLE_PROJECT: omgnetwork-288020
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/kms_account.key.json
  extraVolumes:
    - type: secret
      name: "kms-creds"
    - type: secret
      name: omgnetwork-certs-ck6hgfbb79
  affinity: null
  dev:
    enabled: false
  standalone:
    enabled: false
ui:
  enabled: true
