global:
  tlsDisable: false
  certSecretName: omgnetwork-certs-h7tk624bf6

injector:
  enabled: false

server:
  dataStorage:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

  auditStorage:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

  ha:
    enabled: true
    replicas: 3

    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = false
        log_level = "debug"
        cluster_name = "omgnetwork-cluster"

        listener "tcp" {
          tls_disable = {{ .Values.global.tlsDisable }}
          tls_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.omgnetwork.io.cert.pem"
          tls_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.omgnetwork.io.key.pem"

          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        seal "gcpckms" {
          region      = "global"
          project     = "omgnetwork-vault"
          key_ring    = "omgnetwork-vault-ring"
          crypto_key  = "omgnetwork-vault-unseal-key"
        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.omgnetwork.io.cert.pem"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.omgnetwork.io.key.pem"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca-chain.cert.pem"
          }

          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.omgnetwork.io.cert.pem"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.omgnetwork.io.key.pem"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca-chain.cert.pem"
          }

          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_client_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.omgnetwork.io.cert.pem"
            leader_client_key_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/vault.omgnetwork.io.key.pem"
            leader_ca_cert_file = "/vault/userconfig/{{ .Values.global.certSecretName }}/ca-chain.cert.pem"
          }
        }

        service_registration "kubernetes" {}
  image:
    repository: vault # TODO: will change to the omgnetwork/vault image
    tag: "1.5.0" # TODO: will change to the appropriate tag for omgnetwork/vault
    pullPolicy: IfNotPresent

  extraEnvironmentVars:
    GOOGLE_REGION: global
    GOOGLE_PROJECT: omgnetwork-vault
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/kms_account.key.json

  extraVolumes:
    - type: secret
      name: "kms-creds"
    - type: secret
      name: "omgnetwork-certs-h7tk624bf6"

  affinity: null

  dev:
    enabled: false

  standalone:
    enabled: false

ui:
  enabled: false
