global:
  tlsDisable: true # TODO: change to enable TLS

injector:
  enabled: false

server:
  image:
    repository: vault # TODO: will change to the omgnetwork/vault image
    tag: "1.5.0" # TODO: will change to the appropriate tag for omgnetwork/vault
    pullPolicy: IfNotPresent

  extraEnvironmentVars:
    GOOGLE_REGION: global
    GOOGLE_PROJECT: immutajeff-vault
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/credentials.json

  extraVolumes:
    - type: secret
      name: "kms-creds"

ui:
  enabled: false

vault:
  config:
    clusterName: "immutajeff"
    logLevel: "debug"

  seal:
    project: "immutajeff-vault"
    region: "global"
    keyRing: "immutajeff-keyring"
    key: "immutajeff-key"
