apiVersion: v2
name: vault
description: A Helm chart for Kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.1

appVersion: 0.0.6

dependencies:
  - name: vault
    version: v0.8.0
    repository: https://helm.releases.hashicorp.com

