apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-acl-init-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "omisego-consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}-acl-init-cleanup
      labels:
        app: {{ .Chart.Name }}
        chart: {{ template "omisego-consul.chart" . }}
        release: {{ .Release.Name }}
        component: acl-init-cleanup
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: acl-init-cleanup
          image: {{ .Values.global.imageK8S }}
          command:
            - consul-k8s
          args:
            - delete-completed-job
            - -k8s-namespace={{ .Release.Namespace }}
            - {{ .Chart.Name }}-acl-init