apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-budget
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "omisego-consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      component: server