apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-server-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      {{- if .Values.global.tlsEnabled }}
      "ca_file": "/etc/tls/ca/tls.crt",
      "cert_file": "/etc/tls/service/tls.crt",
      "key_file": "/etc/tls/service/tls.key",
      "verify_incoming_rpc": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      {{- end }}
      "ports": {
        {{- if .Values.global.tlsEnabled }}
        "http": -1,
        "https": 8501
        {{- else }}
        "http": 8500
        {{- end }}
      },
      "primary_datacenter":"{{ .Values.global.datacenter }}",
      "acl": {
          "enabled": true,
          "default_policy": "deny",
          "down_policy": "extend-cache"
      }
    }
  vault.hcl: |
    service "vault" {
      policy = "write"
    }

    key_prefix "vault/" {
      policy = "write"
    }

    agent_prefix "" {
      policy = "write"
    }

    node_prefix "" {
      policy = "write"
    }
    
    session_prefix "" {
      policy = "write"
    }
