apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "omisego-vault.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: server
