apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-server-config
  namespace: {{ .Release.Namespace }}
data:
  config.hcl: |
    listener "tcp" {
      address = "127.0.0.1:8200"
      {{- if .Values.global.tlsEnabled }}
      tls_disable = 0
      tls_cert_file = "/etc/tls/services.pem"
      tls_client_ca_file = "/etc/tls/ca.pem"
      tls_key_file = "/etc/tls/services-key.pem"
      {{- else }}
      tls_disabled = 1
      {{- end }}
    }

    seal "transit" {
      address = "{{ .Values.server.unseal.address }}"
      disable_renewal = "true"
      key_name = "autounseal"
      mount_path = "transit/"
      tls_ca_cert = "/etc/tls/ca.pem"
      token = "{{ .Values.server.unseal.token }}"
    }

    storage "consul" {
      {{- if .Values.global.tlsEnabled }}
      scheme = "https"
      address = "omisego-consul-server:8501"
      tls_ca_file = "/etc/tls/ca.pem"
      tls_cert_file = "/etc/tls/services.pem"
      tls_key_file = "/etc/tls/services-key.pem"
      {{- else }}
      address = "omisego-consul-server:8500"
      {{- end }}
      path = "vault/"
      disable_registration = "true"
      ha_enabled = "true"
      token = "{{ .Values.server.acl.token }}"
    }

    ui = "true"
