global:
  tlsEnabled: true
  certificatesSecretNamePrefix: ""

  image: "consul:1.7.1"
  imageK8S: "hashicorp/consul-k8s:0.12.0"
  # image: "192.168.64.1:5000/consul:1.7.1"
  # imageK8S: "192.168.64.1:5000/hashicorp/consul-k8s:0.12.0"
  pullPolicy: IfNotPresent

  domain: consul
  datacenter: dc1

  gossipEncryption:
    secretName: ""
    secretKey: ""

server:
  replicas: 3
  bootstrapExpect: 3

