apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "backend-consul.name" . }}-vault-acl
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "backend-consul.name" . }}
    chart: {{ template "backend-consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: consul-vault-acl-init
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ template "backend-consul.name" . }}-vault-acl-init
      labels:
        app: {{ template "backend-consul.name" . }}
        chart: {{ template "backend-consul.chart" . }}
        release: {{ .Release.Name }}
        component: consul-vault-acl-init
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-consul-server-acl-init
      containers:
        - name: vault-acl
          image: {{ .Values.global.image }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONSUL_SERVER_PORT
              value: {{ if .Values.global.tls.enabled }}"8501"{{ else }}"8500"{{ end }}
            {{- if .Values.global.tls.enabled }}
            - name: CONSUL_HTTP_SSL
              value: "true"
            - name: CONSUL_CACERT
              value: /consul/tls/ca/tls.crt
            {{- end }}
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-consul-bootstrap-acl-token
                  key: token
          command:
            - "/bin/sh"
            - "-ec"
            - |
              export CONSUL_HTTP_ADDR="${HOST_IP}:${CONSUL_SERVER_PORT}"
              consul acl policy create -name vault-service -rules @/consul/config/vault.hcl -datacenter {{ .Values.global.datacenter }}
              consul acl token create -description "Token for Vault" -policy-name vault-service -datacenter {{ .Values.global.datacenter }}
          volumeMounts:
            - name: tls-ca-cert
              mountPath: /consul/tls/ca
            - name: extra-config
              mountPath: /consul/config
      volumes:
        - name: tls-ca-cert
          secret:
            secretName: {{ .Release.Name }}-consul-ca-cert
        - name: extra-config
          configMap:
            name: {{ template "backend-consul.name" . }}-tls-vaultacl-config
