name: CI - batch-submitter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-lint:
    name: Run batch-submitter Test Suite on Node ${{matrix.node}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '10', '12', '14' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # START DEPENDENCY CACHING
      - name: Cache root deps
        uses: actions/cache@v1
        id: cache_base
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('package.json') }}

      - name: Cache batch-submitter deps
        uses: actions/cache@v1
        id: cache_batch-submitter
        with:
          path: packages/batch-submitter/node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('packages/batch-submitter/package.json') }}

      # END DEPENDENCY CACHING

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
        env:
          PKGS: "batch-submitter"

      - name: Build
        run: |
          yarn clean
          yarn build
        env:
          PKGS: "batch-submitter"

      - name: Test
        run: yarn test
        env:
          PKGS: "batch-submitter"
