name: CI - gas-profiler

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-lint:
    name: Run gas-profiler Test Suite on Node ${{matrix.node}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '10', '11' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # START DEPENDENCY CACHING
      - name: Cache root deps
        uses: actions/cache@v1
        id: cache_base
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('package.json') }}

      - name: Cache gas-profiler
        uses: actions/cache@v1
        id: cache_gas-profiler
        with:
          path: packages/gas-profiler/node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('packages/gas-profiler/package.json') }}

      # END DEPENDENCY CACHING

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
        env:
          PKGS: "gas-profiler"

      - name: Build
        run: |
          yarn clean
          yarn build
        env:
          PKGS: "gas-profiler"

      - name: Test
        run: yarn test
        env:
          PKGS: "gas-profiler"
