name: CI - ovm-toolchain

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-lint:
    name: Run ovm-toolchain Test Suite on Node ${{matrix.node}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '10', '12', '14' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # START DEPENDENCY CACHING
      - name: Cache root deps
        uses: actions/cache@v1
        id: cache_base
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('package.json') }}

      - name: Cache ovm toolchain deps
        uses: actions/cache@v1
        id: cache_ovm-toolchain
        with:
          path: packages/ovm-toolchain/node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('packages/ovm-toolchain/package.json') }}

      # END DEPENDENCY CACHING

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
        env:
          PKGS: "ovm-toolchain"

      - name: Build
        run: |
          yarn clean
          yarn build
        env:
          PKGS: "ovm-toolchain"

      - name: Test
        run: yarn test
        env:
          PKGS: "ovm-toolchain"
