name: integration

on:
  push:
    branches:
      - master
      - '*rc'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-


      - name: Build the services
        working-directory: ./ops
        run: ./scripts/build-ci.sh

  integration:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Monorepo tests
      - uses: actions/checkout@v2
      - name: Bring the stack up and wait for the sequencer to be ready
        working-directory: ./ops
        run: docker-compose up -d && ./scripts/wait-for-sequencer.sh

      - name: Run the integration tests
        working-directory: ./integration-tests
        run: |
            yarn build:contracts
            yarn build:contracts:ovm
            yarn test:integration
        env:
          FORCE_COLOR: 1
          ENABLE_GAS_REPORT: 1

      - name: Print gas report
        run: cat integration-tests/gas-report.txt

  examples:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Examples Tests
      - uses: actions/checkout@v2

      - name: Install and build hardhat example
        working-directory: ./examples/hardhat
        run: |
          yarn

      - name: Test & deploy hardhat-example on hardhat (regression)
        working-directory: ./examples/hardhat
        run: |
          yarn deploy
          yarn test:integration

      - name: Test & deploy hardhat-example on Optimism
        working-directory: ./examples/hardhat
        run: |
          yarn deploy:ovm
          yarn test:integration:ovm

      - name: Install and build hardhat example
        working-directory: ./examples/waffle
        run: |
          yarn

      - name: Test & deploy waffle-example on waffle (regression)
        working-directory: ./examples/waffle
        run: |
          yarn compile
          yarn test:integration

      - name: Test & deploy waffle-example on Optimism
        working-directory: ./examples/waffle
        run: |
          yarn compile:ovm
          yarn test:integration:ovm
