name: Welcome to GITM

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/*'

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Welcome Message
        run: echo "Welcome to GITM"
