apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-consul
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "omisego.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- if not .Values.global.tlsEnabled }}
    - name: http
      port: 8500
      targetPort: 8500
    {{- end }}
    {{- if .Values.global.tlsEnabled }}
    - name: https
      port: 8501
      targetPort: 8501
    {{- end }}
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
  selector:
    app: {{ .Chart.Name }}
    release: "{{ .Release.Name }}"
    component: consul-server
