apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-consul
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "omisego.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-consul
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "omisego.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - create
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs:
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-consul
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "omisego.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-consul
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-consul
    namespace: {{ .Release.Namespace }}
